[project]
name = "dependency"
version = "0.1.0"
authors = [
    { name = "Charlie Marsh", email = "charlie.r.marsh@gmail.com" }
]
requires-python = ">=3.12"
dependencies = ["iniconfig"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
